# To run docs locally:
# docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material
# and open http://localhost:8000/
site_name: Website Continuous Deployment & Delivery
theme:
  name: material

nav:
  - Overview: index.md
  - how-it-works.md
  - Operator Manual:
      - Overview: operator-manual/index.md
      - operator-manual/configuration.md
  - User Guide:
      - Overview: user-guide/index.md
      - user-guide/website-specification.md
      - user-guide/website-management.md
  - Developer Guide:
      - Overview: developer-guide/index.md
      - developer-guide/project-structure.md
      - developer-guide/running-locally.md
      - developer-guide/website-performance-tests.md
      - developer-guide/release.md
  - support.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences