apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: spaship-operator-build
  labels:
    name: spaship
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/spaship/operator.git"
# The another way how to pass Dockerfile
#    dockerfile: |
#      FROM quay.io/spaship/operator-jvm:${TAG}
#      USER root
#      RUN curl -k ${CA_CERT_URL} --create-dirs -o /usr/share/pki/ca-trust-source/anchors/website-cd-ca.crt && update-ca-trust
#      USER 1001
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: "manifests/customca/Dockerfile.operator"
      # Use "env" instead of "buildArgs" when using "dockerfile" as above
      buildArgs:
        - name: CA_CERT_URL
          value: https://password.corp.redhat.com/RH-IT-Root-CA.crt
        - name: TAG
          value: latest
  output:
    to:
      kind: ImageStreamTag
      name: 'spaship-operator-jvm:latest'
#      kind: 'DockerImage'
#      name: 'my-registry.mycompany.com:5000/spaship/operator-jvm:latest'
    pushSecret:
      name: 'push-secret'
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: spaship-operator-jvm

