apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: websitecd-operator-build
  labels:
    name: websitecd
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/websitecd/operator.git"
    contextDir: "service"
    dockerfile: |
      FROM quay.io/websitecd/operator-jvm
      USER root
      RUN curl -k ${CA_CERT_URL} --create-dirs -o /usr/share/pki/ca-trust-source/anchors/website-cd-ca.crt && update-ca-trust
      USER 1001
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'quay.io/websitecd/operator-jvm'
      env:
        - name: CA_CERT_URL
          value: https://password.corp.redhat.com/RH-IT-Root-CA.crt
  output:
    to:
      kind: ImageStreamTag
      name: 'websitecd-operator-jvm:latest'
#      kind: 'DockerImage'
#      name: 'my-registry.mycompany.com:5000/myimages/myimage:tag'
#      pushSecret:
#        name: 'push-secret'

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: websitecd-operator-jvm

