apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spaship-website
  labels:
    spaship: user
roleRef:
  kind: ClusterRole
  name: spaship-website
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User
    name: quicklab
