apiVersion: v1
kind: Service
metadata:
  name: websitecd-operator
  labels:
    app: websitecd-operator
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
  selector:
    app: websitecd-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websitecd-operator
spec:
  selector:
    matchLabels:
      app: websitecd-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: websitecd-operator
    spec:
      serviceAccountName: deployer
      containers:
        - name: operator
          image: "websitecd/operator-jvm:latest"
          livenessProbe:
            httpGet:
              path: "/health/live"
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: "/health/ready"
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: "websitecd-operator-config"
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: websitecd-operator
spec:
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: websitecd-operator
    weight: 100
  wildcardPolicy: None