---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: websites.websitecd.io
spec:
  group: websitecd.io
  scope: Namespaced
  names:
    kind: Website
    singular: website
    plural: websites
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                gitUrl:
                  type: string
                branch:
                  type: string
                dir:
                  type: string
                  default: .
                sslVerify:
                  type: boolean
                  default: true
                webhookSecret:
                  type: string
                envs:
                  type: object
                  properties:
                    included:
                      type: array
                      items:
                        type: string
                    excluded:
                      type: array
                      items:
                        type: string
              required:
                - gitUrl
                - branch
                - webhookSecret
      additionalPrinterColumns:
        - name: Git URL
          type: string
          description: Website Git URL
          jsonPath: .spec.gitUrl
        - name: Branch
          type: string
          description: Git branch
          jsonPath: .spec.branch
        - name: Dir
          type: string
          description: Sub directory within git repo
          jsonPath: .spec.dir
        - name: SSL Verify
          type: string
          description: Performs SSL verification
          jsonPath: .spec.sslVerify
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: websitecd-operator-config
data:
  APP_OPERATOR_ROUTER_MODE: 'ingress'
  APP_OPERATOR_WEBSITE_DOMAIN: 'minikube.info'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: websitecd-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: websitecd-operator
rules:
  - apiGroups: [ "websitecd.io" ]
    resources: [ "websites" ]
    verbs: [ "watch", "list" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [  "ingresses" ]
    verbs: [ "create", "update", "get", "watch", "list" ]
  - apiGroups: [ "" ]
    resources: [  "configmaps", "services", "namespaces" ]
    verbs: [ "create", "update", "get", "watch", "list" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: websitecd-operator
roleRef:
  kind: ClusterRole
  name: websitecd-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: websitecd-operator
    namespace: websitecd
---
apiVersion: v1
kind: Service
metadata:
  name: websitecd-operator
  labels:
    app: websitecd-operator
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
  selector:
    app: websitecd-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websitecd-operator
spec:
  selector:
    matchLabels:
      app: websitecd-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: websitecd-operator
    spec:
      serviceAccountName: websitecd-operator
      containers:
        - name: operator
          image: "quay.io/websitecd/operator-jvm"
          livenessProbe:
            httpGet:
              path: "/health/live"
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: "/health/ready"
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: "websitecd-operator-config"
